### ISSUE TITLE
received_error

### ISSUE THREAD

**Issue by bennetnetan** [erickogi/Mpesaphp#1]
{ "requestId":"13361-139781-1", "errorCode": "400.002.02", "errorMessage": "Bad Request - Invalid CallBackURL" }
What_could_the_issue_be

**Comment by erickogi** [comment]
the url you append when doing the stk should be a valid url ie (http://www.yourdomian.co.ke/callbackfile

**Comment by erickogi** [comment]
You should use a valid url for the callback (http://www.yourdomaim.com/callback.php)
