### ISSUE TITLE
Database columns

### ISSUE THREAD

**Issue by peter-mayeku** [erickogi/Mpesaphp#2]
Hi Eric,
Could you help out with the database columns that receive the stk response from safaricom

**Comment by erickogi** [comment]
For this case since its just an example i just stored the response as plain text but you could do more by parsing the response 

CREATE TABLE `mpesa_callback` (
  `id` int(11) NOT NULL,
  `response` varchar(255) NOT NULL,
  `created_at` datetime NOT NULL
) ENGINE=MyISAM DEFAULT CHARSET=latin1;

**Comment by peter-mayeku** [comment]
Thanks Eric, It worked like charm

**Comment by erickogi** [comment]
Cool..
